# ✅ BANCO DE DADOS — PostgreSQL (Neon)
spring.datasource.url=jdbc:postgresql://ep-late-hall-av2tkpnw.c-11.us-east-1.aws.neon.tech:5432/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_HuC3RzYoIP4b
spring.datasource.driver-class-name=org.postgresql.Driver


# ✅ JPA / Hibernate — PostgreSQL
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


# ✅ PORTA DA API
server.port=8080


# ☁️ CLOUDINARY — ARMAZENAMENTO DE FOTOS
cloudinary.cloud-name=vmcaoh90
cloudinary.api-key=338838296183579
cloudinary.api-secret=2j4ZwxoRZx6e2FWOLahDXF8ZE5c